# Generated by Django 5.2.4 on 2025-07-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdete', models.IntegerField()),
                ('enddete', models.CharField(max_length=200)),
                ('taskname', models.CharField(max_length=200)),
            ],
        ),
    ]
